library(dplyr)
temp <- read.csv("C:\\Users\\vikra\\OneDrive - National College of Ireland\\MSc Data Analytics\\Data Warehousing and Bussiness Intelligence\\Project\\Final CSVs\\AirlineDetails1.csv")
tempCon <- temp %>% arrange(CountryID) %>% select(CountryID, Country, Country.Code)
tempCon2 <- temp %>% arrange(CountryID) %>% select(CountryID, Country, Country.Code)
tempCon3 <- temp %>% arrange(CountryID) %>% select(CountryID, Country, Country.Code)
tempCon4 <- temp %>% arrange(CountryID) %>% select(CountryID, Country, Country.Code)
tempCon5 <- temp %>% arrange(CountryID) %>% select(CountryID, Country, Country.Code)
tempCon6 <- temp %>% arrange(CountryID) %>% select(CountryID, Country, Country.Code)
tempCon <- rbind(tempCon, tempCon2)
tempCon <- rbind(tempCon, tempCon3)
tempCon <- rbind(tempCon, tempCon4)
tempCon <- rbind(tempCon, tempCon5)
tempCon <- rbind(tempCon, tempCon6)
tempCon <- tempCon %>% arrange(CountryID)
write.csv(tempCon, file = "C:\\Users\\vikra\\OneDrive - National College of Ireland\\MSc Data Analytics\\Data Warehousing and Bussiness Intelligence\\Project\\Final CSVs\\Country.csv", row.names = F)
